const songs = [
  { artist: "S3RL", title: "Feel the Melody" , spotifyId: "4Y1fuU6L7Zw4YOaQxLLCuO?si=9f1b59cf93de491f" },
  { artist: "S3RL", title: "Heaven is a Rave" , spotifyId: "6Sk5twlAkUN8PY0rS3nrux?si=2264b21004774343" },
  { artist: "S3RL", title: "Sky rocket" , spotifyId: "77ZCJYncyEOwcyTpYNDGqN?si=b3de635c928e450e" },
  { artist: "S3RL", title: "Avaline" , spotifyId: "0ESbNfWJ7eynLWjsJSSycQ?si=7018290495274f14" },
  { artist: "S3RL", title: "History Maker" , trackId: 6788048868, spotifyId: "4Z8qTY6w8XEqKVEqnhoPyD?si=737c3cd0dc37490b" },
  { artist: "S3RL", title: "Wont Let You Go", trackId: 6766751065, spotifyId: "645hWDD76fIywWIt9jdGbo?si=d9bb143b794449b7" },
  { artist: "S3RL", title: "Catchit" , spotifyId: "0kOHUnzPaZbMEre6v3YOb4?si=7dc89588d0cd4d3c" },
  { artist: "S3RL", title: "Trillium(feat Sara)" , spotifyId: "6vTO3s6hmImIPPfFcaqz0O?si=31f18a7358ab4e2b" },
  { artist: "S3RL", title: "Internet Baby" , spotifyId: "0MAMKSzCQ8nnaalifFWPkb?si=c90ff0334bd44d4f" },
  { artist: "S3RL", title: "Everytime I Look At You" , trackId: 400109506, spotifyId: "7t3b55U4hjAxkgrKtKii4q?si=f334203da4fc4484" },
  { artist: "S3RL", title: "And We Go" , spotifyId: "3D4EzbnnV8MsBjKiVN3rbJ?si=2edb6b6bd7e443a2" },
  { artist: "S3RL", title: "Otaku Boy" , spotifyId: "00KIQkm2QYUCIl2MrFeJmP?si=171c49f63c7c4474" },
  { artist: "S3RL", title: "R4v3 B0y" , trackId: 6770671589, spotifyId: "7o24r1gcmTVz5yPMU4Hqyz?si=5a3e3bb5e6544b48" },
  { artist: "S3RL", title: "Genre Police" , spotifyId: "7zHIGsXaBHEjDiQMGzwef7?si=83841b3768ec4251" },
  { artist: "S3RL", title: "Unicorn" , spotifyId: "1JTvJyx3YteJ0aNkO2Dkjy?si=7f6164b6ce684afb" },
  { artist: "S3RL", title: "Negative XP" , spotifyId: "60rIQcLTLJD7CXx4flOXrl?si=af60c09020554dae" },
  { artist: "S3RL", title: "You Are Mine" , spotifyId: "0VKC7lXl2VPiNHA9WCWhDg?si=3544dd15f5004f61" },
  { artist: "S3RL", title: "Dopamine" , spotifyId: "6iJeBZtPLiGqmXCsG21dfp?si=773b34e81a5141a0" },
  { artist: "S3RL", title: "Pretty Rave Girl" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Sek-c-Raver" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Pika Girl" , trackId: 6768157422, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "MTC" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Bass Slut" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Raver Dimension" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Rainbow Girl" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Little Kandi Raver" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Friendzoned" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Keep On Raving Baby" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Bass and the Melody" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "All That I Need" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Press Play Walk Away" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Happy Hardcore Tonight" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Neon Genesis" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Doki Doki" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Dealer" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Break Em" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Shoulder Boulders" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Stay" , trackId: 476212020, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Weekend" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Into Overdrive" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Rave Forever" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "We All Scream" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Here We Go" , trackId: 405515346, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Freakshow" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Boy Slut" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Stopping For Nothing" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Together" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "My Girlfriend is a Raver" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Let the Music Take Control" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "What We Do" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Neko Nation" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Make You Move" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "It's Time 2 Roll" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "MTC2" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Hentai" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Forever" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Click Bait" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Punch the Gas" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "To Da Rave" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "When I Die" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Space Invader" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Music Is My Saviour" , trackId: 6769793278, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Addict" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Public Joint" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Transformers" , trackId: 405074665, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Tell Me What You Want" , trackId: 6770670586, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "DJ Whore" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Planet Rave" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Over the Rainbow" , trackId: 6770670016, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "I'll See You Again" , trackId: 1845838859, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Kamehameha" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Fan Service" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Dance More" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "The Bass & The Melody 2" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Nostalgic" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Zero Fucks Given" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Put Your phones up" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Close My Eyes S3RL remix" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Every single day" , trackId: 405581709, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Superhero s3rl remix" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Now that ive found you" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Feel the flow" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "FM-200" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "It Went (feat.Jesskah)" , trackId: 414444052, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Stick Together (A.B vs. Finnbarr) [S3RL Remix]" , spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Heart thief" , trackId: 6798350413, spotifyId: "XXXXXXXXXXXXXXXXXXXXXXXX" },
  { artist: "S3RL", title: "Airhead" },

]

export default songs