const songs = [
  { artist: "S3RL", title: "Trillium(feat Sara)" },
  { artist: "S3RL", title: "Feel the Melody" },
  { artist: "S3RL", title: "My Girlfriend is a Raver" },
  { artist: "S3RL", title: "Avaline" },
  { artist: "S3RL", title: "Heaven is a Rave" },
  { artist: "S3RL", title: "Wont Let You Go", trackId: 6766751065 },
  { artist: "S3RL", title: "Catchit" },
  { artist: "S3RL", title: "Internet Baby" },
  { artist: "S3RL", title: "Everytime I Look At You" , trackId: 400109506},
  { artist: "S3RL", title: "And We Go" },
  { artist: "S3RL", title: "History Maker" , trackId: 6788048868},
  { artist: "S3RL", title: "Otaku Boy" },
  { artist: "S3RL", title: "R4v3 B0y" , trackId: 6770671589},
  { artist: "S3RL", title: "Genre Police" },
  { artist: "S3RL", title: "Unicorn" },
  { artist: "S3RL", title: "Negative XP" },
  { artist: "S3RL", title: "You Are Mine" },
  { artist: "S3RL", title: "Dopamine" },
  { artist: "S3RL", title: "Pretty Rave Girl" },
  { artist: "S3RL", title: "Sek-c-Raver" },
  { artist: "S3RL", title: "Pika Girl" , trackId: 6768157422},
  { artist: "S3RL", title: "MTC" },
  { artist: "S3RL", title: "Bass Slut" },
  { artist: "S3RL", title: "Raver Dimension" },
  { artist: "S3RL", title: "Rainbow Girl" },
  { artist: "S3RL", title: "Little Kandi Raver" },
  { artist: "S3RL", title: "Friendzoned" },
  { artist: "S3RL", title: "Keep On Raving Baby" },
  { artist: "S3RL", title: "Bass and the Melody" },
  { artist: "S3RL", title: "All That I Need" },
  { artist: "S3RL", title: "Press Play Walk Away" },
  { artist: "S3RL", title: "Happy Hardcore Tonight" },
  { artist: "S3RL", title: "Neon Genesis" },
  { artist: "S3RL", title: "Doki Doki" },
  { artist: "S3RL", title: "Dealer" },
  { artist: "S3RL", title: "Break Em" },
  { artist: "S3RL", title: "Shoulder Boulders" },
  { artist: "S3RL", title: "Stay" , trackId: 476212020},
  { artist: "S3RL", title: "Weekend" },
  { artist: "S3RL", title: "Into Overdrive" },
  { artist: "S3RL", title: "Rave Forever" },
  { artist: "S3RL", title: "We All Scream" },
  { artist: "S3RL", title: "Here We Go" , trackId: 405515346},
  { artist: "S3RL", title: "Freakshow" },
  { artist: "S3RL", title: "Boy Slut" },
  { artist: "S3RL", title: "Stopping For Nothing" },
  { artist: "S3RL", title: "Together" },
  { artist: "S3RL", title: "Let the Music Take Control" },
  { artist: "S3RL", title: "What We Do" },
  { artist: "S3RL", title: "Neko Nation" },
  { artist: "S3RL", title: "Make You Move" },
  { artist: "S3RL", title: "It's Time 2 Roll" },
  { artist: "S3RL", title: "MTC2" },
  { artist: "S3RL", title: "Hentai" },
  { artist: "S3RL", title: "Forever" },
  { artist: "S3RL", title: "Click Bait" },
  { artist: "S3RL", title: "Punch the Gas" },
  { artist: "S3RL", title: "To Da Rave" },
  { artist: "S3RL", title: "When I Die" },
  { artist: "S3RL", title: "Space Invader" },
  { artist: "S3RL", title: "Music Is My Saviour" , trackId: 6769793278},
  { artist: "S3RL", title: "Addict" },
  { artist: "S3RL", title: "Public Joint" },
  { artist: "S3RL", title: "Transformers" , trackId: 405074665},
  { artist: "S3RL", title: "Tell Me What You Want" , trackId: 6770670586},
  { artist: "S3RL", title: "DJ Whore" },
  { artist: "S3RL", title: "Planet Rave" },
  { artist: "S3RL", title: "Over the Rainbow" , trackId: 6770670016},
  { artist: "S3RL", title: "I'll See You Again" , trackId: 1845838859},
  { artist: "S3RL", title: "Kamehameha" },
  { artist: "S3RL", title: "Fan Service" },
  { artist: "S3RL", title: "Dance More" },
  { artist: "S3RL", title: "The Bass & The Melody 2" },
  { artist: "S3RL", title: "Nostalgic" },
  { artist: "S3RL", title: "Zero Fucks Given" },
  { artist: "S3RL", title: "Put Your phones up" },
  { artist: "S3RL", title: "Close My Eyes S3RL remix" },

]

export default songs